### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.1

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @jakirkham :)

**Comment by jakirkham** [comment]
Thanks @bgruening. If that doesn't fix it, please let us know.

**Comment by jakirkham** [comment]
FYI we are rebuilding for NumPy 1.13 ATM. So things might be a bit sluggish with the CIs.

**Comment by rvalieris** [comment]
looks like it worked py35 and py36 builds are available now.

**Comment by jakirkham** [comment]
Cool. I tried to trigger an old CircleCI build to see if we could get Python 3.4 as well, but am not very hopeful that it will work. It is based on a very old re-rendering. We can wait and see though.

**Comment by jakirkham** [comment]
This should also give us Python 3.6 builds on Windows.

**Comment by bgruening** [comment]
@jakirkham thanks for the merge! You rock!

**Comment by jakirkham** [comment]
Glad to help.

**Pull request merged**
